### ISSUE TITLE
InvalidWeight

### ISSUE THREAD

**Issue by m-vz** [MikeIvanichev/norma#23]
I'm trying to get this to run on an M1 machine using the example you provide in the `README.md`. The example runs, nothing happens though and after the 10 seconds of sleep, I get an error `InvalidWeight` with the following output:

```
thread '<unnamed>' panicked at /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/norma-0.0.1/src/models/whisper/model.rs:333:80:
called `Result::unwrap()` on an `Err` value: InvalidWeight
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1077:23
   4: norma::models::whisper::model::Model::decode
             at /Users/milan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/norma-0.0.1/src/models/whisper/model.rs:333:29
   5: norma::models::whisper::model::Model::decode_with_fallback
             at /Users/milan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/norma-0.0.1/src/models/whisper/model.rs:176:22
   6: <norma::models::whisper::model::Model as norma::models::Model>::transcribe
             at /Users/milan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/norma-0.0.1/src/models/whisper/model.rs:90:28
   7: norma::Transcriber<T>::run
             at /Users/milan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/norma-0.0.1/src/lib.rs:458:44
   8: norma::Transcriber<T>::blocking_spawn::{{closure}}::{{closure}}
             at /Users/milan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/norma-0.0.1/src/lib.rs:373:40
```

Do you have any clue as to how to get this to run?

**Comment by MikeIvanichev** [comment]
Hi @m-vz, thanks a lot for the report.. The issue has been adressed, you just have to update to norma `0.0.3`.

> The example runs, nothing happens though and after the 10 seconds...

By default the model will transcribe in 25 second increments, so it only starts transcribing after the recording stops ([further reading](https://docs.rs/norma/latest/norma/models/whisper/monolingual/struct.Definition.html#method.set_responsiveness)). 


P.S. If you are running on an M1 mac i'd suggest using `metal` instead of `cpu`. 
You just have to enable the `metal` feature and set the SelectedDevice to Metal
